name: Pull detached upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '22 2 1 * *'
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repo
      - uses: actions/checkout@v2
      # Fetch the history and unshallow the repo so that it can be used
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      # Pull the detached remote and do the magic
      - name: Pull Detached Remote
        uses: litetex/pull-detached-remote@v0.3
        with:
          upstreamrepo: https://github.com/Disassembler0/Win10-Initial-Setup-Script
          upstreambranch: master
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
